# Gymnasium Environment Request and Service message format
# Request
FloatTensor     action # Action
---
# Response
FloatTensor     s_1    # State in the environment after action
FloatTensor     info   # Extra information
